config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated :user do
    root to: "plantings#index", as: :authenticated_root
  end

  root to: "static_pages#index"

  resources :accounts
  get 'account-detail', to: 'accounts#index'
  get 'reactivate', to: 'accounts#reactivate'
  get 'cancel', to: 'accounts#cancel'
  get 'subscribe', to: 'accounts#resubscribe'
  get 'update_cc', to: 'accounts#update_cc'
  post 'coupons', to: 'accounts#coupons'
  post 'suggestion_email', to: 'accounts#suggestion_email'

  resources :crops do
    resources :varietals
  end
  
  get 'dashboard', to: 'dashboard#index'
  # resources :dashboard
  resources :plantings do resources :harvests
  end

  post 'stripe/webhook'
end

app/models/crop.rb
class Crop < ActiveRecord::Base
  has_many :plantings
  has_many :varietals
  before_validation :downcase_fields

  validates :name, :presence => true
  validates_uniqueness_of :name

private
  def downcase_fields
    self.name.downcase!
  end
end

app/controllers/crops_controller.rb
class CropsController < ApplicationController
  before_action :authenticate_user!
  before_action :account?
  before_action :account_active?

  def index
    @crops = Crop.all.order(:name)
  end

  def new
    @crop = Crop.new
  end

  def create
    @crop = Crop.new(crop_params)
    if @crop.save
      flash[:success] = "Your crop was successfully saved."
      redirect_to crops_path
    else
      flash[:error] = "Something went wrong saving your crop."
      redirect_to new_crop_path
    end
  end

  def show
    @crop = Crop.find(params[:id])
    @varietals = @crop.varietals.all.order(:name)
  end

  def edit
    @crop = Crop.find(params[:id])
  end

  def update
    @crop = Crop.find(params[:id])
    if @crop.update(crop_params)
      flash[:success] = "Crop was successfully updated."
      redirect_to crop_path(@crop)
    else
      flash[:error] = "There was a problem saving your crop."
      render :edit
    end
  end

private

  def crop_params
    params.require(:crop).permit(:name)
  end
end

app/views/crops/_form.html.erb
<%= form_for @crop do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group dropdown col-sm-12">
    <%= f.text_field :name, :class => 'form-control' %>
  </div>

  <div class="form-group col-sm-12">
    <%= f.submit "Submit Record", :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/crops/_planting_fields.html.erb
<%= f.hidden_field :user_id, :value => current_user.id %>
<div class="form-group dropdown col-sm-12">
  <%= f.label "Planting Date", :class => 'control-label col-sm-2' %>
  <%= date_select :planting, :date, :class => 'form-control datepicker' %>
</div>

<div class="form-group col-sm-12">
  <%= f.label "Planting Size", :class => 'control-label col-sm-2' %>
  <%= f.radio_button :plot_id, "1", :checked => true, :class => 'radio-inline' %> Tray
  <%= f.radio_button :plot_id, "2", :disabled => true, :class => 'radio-inline' %> Bed
</div>

<div class="form-group col-sm-12">
  <%= f.label "Quantity of Seeds", :class => 'control-label col-sm-2' %>
  <%= f.number_field :quantity, :class => 'text_field col-sm-2', :step => 'any' %>
    <div class="form-group col-sm-2">
      <%= f.radio_button :measurement_id, "1", :checked => true, :class => 'radio-inline' %> Ounces
      <%= f.radio_button :measurement_id, "2", :class => 'radio-inline' %> Grams
    </div>
</div>

<div class="form-group col-sm-12">
  <%= f.label :notes, :class => 'control-label col-sm-2' %>
  <%= f.text_area :notes, :class => 'text_field'  %>
</div>

app/views/crops/_varietal_fields.html.erb
<div class="form-group col-sm-12">
  <%= f.label :varietal, :class => 'control-label col-sm-2' %>
  <%= f.text_field :varietal, :class => 'form-control' %>
</div>

app/views/crops/edit.html.erb
<h1>Edit Crop</h1>
<%= render 'form' %>

app/views/crops/index.html.erb
<h1>Crops List</h1>
<%= link_to "Add a new crop", new_crop_path, :class => 'btn btn-default btn-sm' %>
<ul class='list-unstyled'>
  <% @crops.each do |crop| %>
    <li><%= link_to crop.name, crop_path(crop) %></li>
  <% end %>
</ul>

app/views/crops/new.html.erb
<h1>Enter a new Crop</h1>

<%= render 'form' %>

app/views/crops/show.html.erb
<h1><%= @crop.name.titleize %></h1>
<%= link_to "Edit Crop", edit_crop_path(@crop), :class => "btn btn-default btn-xs" %>
<%= link_to "Back to Crop List", crops_path, :class => "btn btn-default btn-xs" %>

<h3>Variety List for this Crop</h3>
<%= link_to "Add varietal", new_crop_varietal_path(@crop), :class => "btn btn-default btn-xs" %>
<ul class='list-unstyled'>
  <% @varietals.each do |varietal| %>
    <li><%= varietal.name.titleize %> - <%= link_to "Edit", edit_crop_varietal_path(varietal.crop, varietal) %></li>
  <% end %>
</ul>