config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated :user do
    root to: "plantings#index", as: :authenticated_root
  end

  root to: "static_pages#index"

  resources :accounts
  get 'account-detail', to: 'accounts#index'
  get 'reactivate', to: 'accounts#reactivate'
  get 'cancel', to: 'accounts#cancel'
  get 'subscribe', to: 'accounts#resubscribe'
  get 'update_cc', to: 'accounts#update_cc'
  post 'coupons', to: 'accounts#coupons'
  post 'suggestion_email', to: 'accounts#suggestion_email'

  resources :crops do
    resources :varietals
  end
  
  get 'dashboard', to: 'dashboard#index'
  # resources :dashboard
  resources :plantings do resources :harvests
  end

  post 'stripe/webhook'
end

app/models/planting.rb
class Planting < ActiveRecord::Base
  has_one :harvest, dependent: :destroy
  belongs_to :user
  belongs_to :crop
  belongs_to :measurement
  belongs_to :plot
  belongs_to :varietal

  validates :crop_id, :presence => true
  validates :date, :presence => true
  validates :quantity, :presence => true
  validates :varietal_id, :presence => true

end

app/controllers/plantings_controller.rb
class PlantingsController < ApplicationController
  before_action :authenticate_user!
  before_action :account?
  before_action :account_active?

  def index
    @user = current_user
    @plantings = @user.plantings.includes(:harvest)
    @planting = Planting.new
  end

  def show
    @planting = Planting.find(params[:id])
  end

  def new
    @planting = Planting.new
  end

  def create
    @planting = Planting.new(planting_params)
    if @planting.save
      flash[:success] = "Your planting record was successfully saved."
      redirect_to :root
    else
      flash[:error] = "There was a problem saving your planting record."
      redirect_to :root
    end
  end

  def edit
    @planting = Planting.find(params[:id])
  end

  def update
    @planting = Planting.find(params[:id])
    if @planting.update(planting_params)
      if @planting.harvest.present?
        harvest = @planting.harvest
        harvest.dtm = (harvest.date - @planting.date).to_i
        harvest.save
      end
      flash[:success] = "Planting record successfully updated."
      redirect_to planting_path(@planting)
    else
      flash[:error] = "There was a problem saving your planting record."
      render :edit
    end
  end

  def destroy
    @planting = Planting.find(params[:id])
    @planting.destroy
    flash[:success] = "The planting record was successfully deleted."
    redirect_to :root
  end

private
  def planting_params
    params.require(:planting).permit(:date, :crop_id, :quantity, :measurement_id, :notes, :plot_id, :user_id, :varietal_id)
  end
end

app/views/plantings/_crop_fields.html.erb
<%= f.label :name, :class => 'control-label col-sm-2' %>
<%= f.text_field :name, :class => 'form-control' %>

app/views/plantings/_form.html.erb
<fieldset class="information-box">
  <legend>Add a New Planting Record</legend>
<%= form_for @planting, :html => {:class => "form-horizontal"} do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="form-group dropdown col-sm-12">
    <%= f.label "Planting Date", :class => 'control-label col-sm-2' %>
    <div class="col-sm-5">
      <%= date_select :planting, :date, :class => 'datepicker' %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label "Planting Size", :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.radio_button :plot_id, 1, label: "Tray", :checked => true, inline: true %> Tray
      <%= f.radio_button :plot_id, 2, :disabled => true, label: "Bed", :class => 'radio-inline' %> <span class="disabled">Bed</span>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label :crop, :class => 'control-label col-sm-2' %>
    <div class="col-sm-3">
      <%= f.collection_select :crop_id, Crop.order(:name), :id, :name, { include_blank: true }, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label "Variety", :class => 'control-label col-sm-2' %>
    <div class="col-sm-3">
     <%= f.grouped_collection_select :varietal_id, Crop.order(:name), :varietals, :name, :id, :name, { include_blank: true }, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label "Quantity of Seeds", :class => 'control-label col-sm-2' %>
    <div class="col-sm-2">
      <%= f.number_field :quantity, :class => 'form-control', :step => 'any' %>
    </div>
      <div class="col-sm-2">
        <%= f.radio_button :measurement_id, "1", :checked => true, :class => 'radio-inline' %> Ounces
        <%= f.radio_button :measurement_id, "2", :class => 'radio-inline' %> Grams
      </div>
  </div>

  <div class="form-group col-sm-12">
    <%= f.label "Planting Notes", :class => 'control-label col-sm-2' %>
    <div class="col-sm-10">
      <%= f.text_area :notes, :class => 'form-control'  %>
    </div>
  </div>

  <div class="col-sm-3 col-sm-offset-2">
    <%= f.submit "Submit Record", :class => 'btn btn-default' %>
  </div>

<% end %>
</fieldset>

app/views/plantings/_harvest_info.html.erb
<% if @planting.harvest.present? %>
  <legend>Harvest Information</legend>
  <dl>
    <dt>Harvest Date</dt>
    <dd><%= @planting.harvest.date.strftime("%B %e, %Y") %></dd>
  </dl>
  <dl>
    <dt>Harvest Yield</dt>
    <dd><%= @planting.harvest.yield %> <%= @planting.harvest.measurement.unit %></dd>
  </dl>
  <dl>
    <dt>Days to Maturity</dt>
    <dd><%= @planting.harvest.dtm %></dd>
  </dl>
  <dl>
    <dt>Harvest Notes</dt>
    <dd><%= @planting.harvest.notes %></dd>
  </dl>
<%= link_to "Edit Harvest", edit_planting_harvest_path(@planting, @planting.harvest), :class => "btn btn-default btn-xs col-xs-offset-2" %>
<% end %>

app/views/plantings/_planting_info.html.erb
<legend><%= @planting.crop.name.titleize %></legend>
<dl>
  <dt>Varietal</dt> 
  <dd><%= @planting.varietal.name.titleize %></dd>
</dl>
<dl>
  <dt>Date Planted</dt>
  <dd><%= @planting.date.strftime("%B %e, %Y") %></dd>
</dl>
<dl>
  <dt>Planting Size</dt>
  <dd><%= @planting.plot.name.titleize %></dd>
</dl>
<dl>
  <dt>Seed Quantity</dt>
  <dd><%= @planting.quantity %> <%= @planting.measurement.unit %></dd>
</dl>
<dl>
  <dt>Planting Notes</dt>
  <dd><%= @planting.notes %></dd>
</dl>

app/views/plantings/_varietal_fields.html.erb
<%= f.label :varietal, :class => 'control-label col-sm-2' %>
<%= f.text_field :varietal, :class => 'form-control' %>

app/views/plantings/edit.html.erb
<%= render partial: "form" %>

app/views/plantings/index.html.erb
<p class="lead">Planting Records</p>

<%= render partial: "form" %>

<% if @plantings.any? %>
  <p class="welcome col-md-12 text-center lead">Beds To Be Harvested</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th class='col-sm-1'>Planting Date</th>
        <th class='col-sm-2'>Crop</th>
        <th class='col-sm-2'>Variety</th>
        <th class='col-sm-1'>Planting Size</th>
        <th class='col-sm-1'>Seed Quantity</th>
        <th class='col-sm-3'>Planting Notes</th>
        <th class='col-sm-1'></th>
        <th class='col-sm-1'></th>
      </tr>
    </thead>
    <tbody>
      <% @plantings.each do |planting| %>
        <% if planting.harvest.blank? %>
          <tr>
            <td><%= planting.date.strftime("%m-%d-%Y") %></td>
            <td><%= planting.crop.name.titleize %></td>
            <td><%= planting.varietal.name.titleize %></td>
            <td><%= planting.plot.name.titleize %></td>
            <td><%= planting.quantity %> <%= planting.measurement.unit %></td>
            <td><%= planting.notes.truncate(40, separator: " ") %></td>
            <td><%= link_to "Add Harvest", new_planting_harvest_path(planting), class: 'btn btn-primary btn-xs' %></td>
            <td>
              <%= link_to planting_path(planting.id) do %>
                <i class="glyphicon glyphicon-eye-open"></i>
              <% end  %>
              <%= link_to edit_planting_path(planting.id) do %>
                <i class="glyphicon glyphicon-edit"></i>
              <% end %>
              <%= link_to planting_path(planting.id), :data => {:confirm => "Are you sure you want to delete this planting record?",
                                                                :method => "delete"} do %>
                <i class="glyphicon glyphicon-remove"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <p class="welcome col-md-12 text-center lead">Harvested Beds</p>
  <table class="table table-hover">
    <thead>
      <tr>
        <th class='col-sm-1'>Harvest Date</th>
        <th class='col-sm-2'>Crop</th>
        <th class='col-sm-2'>Variety</th>
        <th class='col-sm-1'>Planting Size</th>
        <th class='col-sm-1'>Yield Amount</th>
        <th class='col-sm-4'>Harvest Notes</th>
        <th class='col-sm-1'></th>
      </tr>
    </thead>
    <tbody>
      <% @plantings.each do |planting| %>
        <% if planting.harvest.present? %>
          <tr>
            <td><%= planting.harvest.date.strftime("%m-%d-%Y") %></td>
            <td><%= planting.crop.name.titleize %></td>
            <td><%= planting.varietal.name.titleize %></td>
            <td><%= planting.plot.name.titleize %></td>
            <td><%= planting.harvest.yield %> <%= planting.harvest.measurement.unit %></td>
            <td><%= planting.harvest.notes.truncate(55, separator: " ") %></td>
            <td>
              <%= link_to planting_path(planting) do %>
                <i class="glyphicon glyphicon-eye-open"></i>
              <% end %>
              <%= link_to edit_planting_harvest_path(planting, planting.harvest) do %>
                <i class="glyphicon glyphicon-edit"></i>
              <% end %>
              <%= link_to planting_path(planting.id), :data => {:confirm => "Are you sure you want to delete this planting record?",
                                                                :method => "delete"} do %>
                <i class="glyphicon glyphicon-remove"></i>
              <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/plantings/show.html.erb
<fieldset class="information-box">
  <p class="lead">Planting Record</p>

  <%= render 'planting_info' %>
  <%= link_to "Edit Planting", edit_planting_path(@planting), :class => "btn btn-default btn-xs col-xs-offset-2" %>
  <br />
  <%= render 'harvest_info' %>
</fieldset>
<br />
<%= link_to "Planting Records", :root, :class => "btn btn-default" %>