config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated :user do
    root to: "plantings#index", as: :authenticated_root
  end

  root to: "static_pages#index"

  resources :accounts
  get 'account-detail', to: 'accounts#index'
  get 'reactivate', to: 'accounts#reactivate'
  get 'cancel', to: 'accounts#cancel'
  get 'subscribe', to: 'accounts#resubscribe'
  get 'update_cc', to: 'accounts#update_cc'
  post 'coupons', to: 'accounts#coupons'
  post 'suggestion_email', to: 'accounts#suggestion_email'

  resources :crops do
    resources :varietals
  end
  
  get 'dashboard', to: 'dashboard#index'
  # resources :dashboard
  resources :plantings do resources :harvests
  end

  post 'stripe/webhook'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farm Sheets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if content_for?(:head) %>
    <%= yield(:head) %>
  <% end %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-54111182-3', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body>

  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Farm Sheets", root_path, class: "navbar-brand" %>
      </div>

      <div>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Your Account", account_detail_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Start Your Free Trial", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container content">
    <%= flash_messages %>
    <%= yield %>
  </div>

</body>
</html>