config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { registrations: "registrations" }

  authenticated :user do
    root to: "plantings#index", as: :authenticated_root
  end

  root to: "static_pages#index"

  resources :accounts
  get 'account-detail', to: 'accounts#index'
  get 'reactivate', to: 'accounts#reactivate'
  get 'cancel', to: 'accounts#cancel'
  get 'subscribe', to: 'accounts#resubscribe'
  get 'update_cc', to: 'accounts#update_cc'
  post 'coupons', to: 'accounts#coupons'
  post 'suggestion_email', to: 'accounts#suggestion_email'

  resources :crops do
    resources :varietals
  end
  
  get 'dashboard', to: 'dashboard#index'
  # resources :dashboard
  resources :plantings do resources :harvests
  end

  post 'stripe/webhook'
end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  def process_subscription
    @amount = 500
    customer = Stripe::Customer.create(
      :email => stripeEmail,
      :card  => stripeToken,
      :plan => 232
    )
    self.stripe_customer_id = customer.id
    self.stripe_status = customer.subscriptions.data.first.status
  end

  def cancel_subscription
    customer = Stripe::Customer.retrieve(stripe_customer_id)
    customer.subscriptions.retrieve(customer.subscriptions.data.first.id).delete(:at_period_end => true)
  end

  def reactivate_subscription
    customer = Stripe::Customer.retrieve(stripe_customer_id)
    subscription = customer.subscriptions.retrieve(customer.subscriptions.data.first.id)
    subscription.plan = "232"
    subscription.save
  end

  def subscribe
    customer = Stripe::Customer.retrieve(stripe_customer_id)
    customer.subscriptions.create(:plan => "232", :trial_end => "now")
  end

  def apply_coupon(coupon)
    customer = Stripe::Customer.retrieve(stripe_customer_id)
    customer.coupon = coupon
    customer.save
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :account?, except: [:new, :create]

  def new
    @user = current_user
    @account = @user.build_account
  end

  def create
    @user = current_user
    @account = @user.build_account account_params.merge(stripeEmail: stripe_params['stripeEmail'], 
                                                        stripeToken: stripe_params['stripeToken'], 
                                                        stripeTokenType: stripe_params['stripeTokenType'])
    raise "Please, check account errors" unless @account.valid?
    @account.process_subscription
    if @account.save
      redirect_to :root
    else
      render :new
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to account_detail_path
  end

  def index
    @user = current_user
    @account = @user.account
    @customer = Stripe::Customer.retrieve(@account.stripe_customer_id)
    @card = @customer.sources.retrieve(@customer.sources.data[0].id)
    @stripe = @customer.subscriptions.data[0]
  end

  def cancel
    user = current_user
    account = user.account
    account.cancel_subscription
    redirect_to account_detail_path
  end

  def reactivate
    user = current_user
    account = user.account
    account.reactivate_subscription
    redirect_to account_detail_path
  end

  def resubscribe
    user = current_user
    account = user.account
    account.subscribe
    redirect_to account_detail_path
  rescue Exception => e
    flash[:error] = e.message
    redirect_to account_detail_path
  end

  def coupons
    user = current_user
    account = user.account
    coupon_code = params[:coupon_code]
    account.apply_coupon(coupon_code)
    redirect_to account_detail_path
  rescue Exception => e  
    flash[:error] = e.message
    redirect_to account_detail_path
  end

  def suggestion_email
    user = current_user
    account = user.account
    suggestion = suggestion_params
    AccountNotifier.send_suggestion_email(user, account, suggestion).deliver
    flash[:success] = "Thank you for your suggestion."
    redirect_to account_detail_path
  rescue Exception => e
    flash[:error] = e.message
    redirect_to account_detail_path
  end

private
  def account_params
    params.require(:account).permit(:first_name, :last_name, :user_id)
  end

  def stripe_params
    params.permit(:stripeEmail, :stripeToken, :stripeTokenType)
  end

  def suggestion_params
    params.permit(:category, :body)
  end
end

app/views/accounts/_account_details.html.erb
<fieldset class="information-box">
  <legend>Account Details</legend>
    <dl>
      <dt>Name</dt>
      <dd><%= @account.first_name.titleize %> <%= @account.last_name.titleize %></dd>
    </dl>
    <dl>
      <dt>Email</dt>
      <dd><%= current_user.email %></dd>
    </dl>
    <dl>
      <dt>Account Number</dt> 
      <dd><%= @account.stripe_customer_id %></dd>
    </dl>
      <dl>
        <dt>Account Status</dt> 
        <dd><%= @account.stripe_status.titleize %></dd>
      </dl>
    <% if @stripe.present? %>
      <dl>
        <dt>Plan Name</dt> 
        <dd><%= @stripe.plan.name %></dd>
      </dl>
      <% if @stripe.cancel_at_period_end == true %>
        <dl>
          <dt>Plan End</dt>
          <dd><%= Time.at(@stripe.current_period_end).strftime("%B %e, %Y") %></dd>
        </dl>
        <dl>
          <dd>You elected to cancelled your account.  You may continue to use this account until the end of this subscription period which will end on <%= Time.at(@stripe.current_period_end).strftime("%B %e, %Y") %>.</dd>
        </dl>
        <p><%= link_to 'Reactivate Subscription', reactivate_path %></p>
      <% else %>
        <p><%= link_to 'Cancel Subscription', cancel_path, data: {confirm: 'Are you sure you want to cancel your subscription?'} %></p>
      <% end %>

    <% else %>
      <p>You do not have an active account</p>
      <p><%= link_to 'Resubscribe', subscribe_path %></p>
    <% end %>

    <p><%= link_to "Change your password", edit_user_registration_path %></p>
</fieldset>

app/views/accounts/_credit_card.html.erb
<fieldset class="information-box">
  <legend>Card Details</legend>
  <dl>
    <dt>Card Type</dt>
    <dd><%= @card.brand %></dd>
  </dl>
  <dl>
    <dt>Card Last 4</dt>
    <dd><%= @card.last4 %></dd>
  </dl>
  <dl>
    <dt>Expiration</dt>
    <dd><%= @card.exp_month %>/<%= @card.exp_year %></dd>
  </dl>
</fieldset>

app/views/accounts/_discount.html.erb
<% if @customer.discount.present? %>
  <% if @customer.discount.coupon.valid == true %>
    <fieldset class="information-box">
      <legend>Active Discounts</legend>
      <dl>
        <dt>Type</dt>
        <dd><%= @customer.discount.coupon.id %></dd>
      </dl>
      <dl>
        <dt>Amount</dt>
        <dd><%= @customer.discount.coupon.percent_off %>% off</dd>
      </dl>
      <dl>
        <dt>Discount Duration</dt>
        <dd><%= @customer.discount.coupon.duration_in_months %> months</dd>
      </dl>
      <dl>
        <dt>Discount Start</dt>
        <dd><%= Time.at(@customer.discount.coupon.created).strftime("%B %e, %Y") %></dd>
      </dl>
    </fieldset>
  <% end %>
<% else %>
  <fieldset class="information-box">
    <legend>Add Coupon Code</legend>
    <%= form_tag "/coupons" do %>
      <div>
        <%= text_field_tag "coupon_code" %>
      </div>
<br />
      <%= submit_tag "Apply Coupon", :class => "btn btn-default" %>
    <% end %>
  </fieldset>
<% end %>

app/views/accounts/_suggestion.html.erb
<fieldset class="information-box">
  <legend>Suggestion for Improvement</legend>
  <%= form_tag "/suggestion_email" do %>
    <p class="lead">Help us improve FarmSheets.</p>
    <div class="col-md-4">
      <%= select_tag "category", "<option>Suggestion for Improvement</option><option>Inaccurate Information</option><option>Account Issue</option><option>Other</option>".html_safe, :class => 'form-control' %>
    <br />
    </div>
    <div class="col-md-12">
      <%= text_area_tag "body", '', :class => 'form-control', :rows => '3' %>
    <br />
    </div>
    <div class="col-md-12">
      <%= submit_tag "Send Suggestion", :class => "btn btn-default" %>
    </div>
  <% end %>
</fieldset>

app/views/accounts/index.html.erb
<div class="col-md-6">
  <%= render 'account_details' %>
</div>

<div class="col-md-6">
  <%= render 'credit_card' %>
</div>

<div class="col-md-6">
  <%= render 'discount' %>
</div>

<div class="col-md-12">
  <%= render 'suggestion' %>
</div>

app/views/accounts/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <fieldset class="information-box">
  <h2 class="text-center">New Account</h2>
  <p>Please fill out the information below to continue your account setup</p>

  <%= form_for @account do |f| %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :class => 'form-control col-sm-2' %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class => 'form-control col-sm-2' %>
    </div>
    <h1 class="text-center">Lock in Farm Sheets at the lowest rate</h1>
    <h2 class="text-center">$5/month</h2>

    <p>Purchase Farm Sheets now and lock in this price forever.  We are improving this tool every month with your input.  By joing now and helping us make this tool incredible, you get to keep this rate forever.</p>

    <p>Once we feel this tool is "production ready" it will be priced around $20/month.</p>

    <p>Thanks for your help developing it and enjoy a lifetime of savings!</p>

    <p>- Luke Callahan, Founder of Farmsheets.com</p>
    
    <%= form_tag account_detail_path do %>
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-name="Farm Sheets"
              data-description="$5 a month subscription"
              data-locale="auto"
              data-panelLabel="Subscribe"
              data-email="<%= j current_user.email %>"
              data-allowRememberMe=false>
      </script>
    <% end %>
  <% end %>
  <p>* Your card will not be charged until after the 7 day free trial is over.</p>
  </fieldset>
</div>

app/views/accounts/update_cc.html.erb
update_cc.html.erb